version: '3'
services:

 nginxProxy:
  container_name: reactPortfolioProxy
  image: nginx
  ports:
    - 443:443
    - 80:80
  volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  command: nginx -g 'daemon off;'

 reactportfolioclient:
  container_name: reactPortfolioClient
  ports:
    - 8001
  volumes:
    - ./reactPortfolioClient:/opt/app
    - /opt/app/node_modules/ #Prevent the copy of the node_modules directory
  build:
   context: ./reactPortfolioClient
  command: bash -c "npm i && npm start"

